vim.cmd("call plug#begin('~/.vim/plugged')")

vim.cmd("Plug 'MunifTanjim/nui.nvim'")
vim.cmd("Plug 'Xuyuanp/nerdtree-git-plugin'")
vim.cmd("Plug 'airblade/vim-gitgutter'")
vim.cmd("Plug 'chriskempson/base16-vim'")
vim.cmd("Plug 'duane9/nvim-rg'")
vim.cmd("Plug 'easymotion/vim-easymotion'")
vim.cmd("Plug 'github/copilot.vim'")
vim.cmd("Plug 'godlygeek/tabular'")
vim.cmd("Plug 'ibhagwan/fzf-lua'")
vim.cmd("Plug 'jackMort/ChatGPT.nvim'")
vim.cmd("Plug 'junegunn/vim-emoji'")
vim.cmd("Plug 'ludovicchabant/vim-gutentags'")
vim.cmd("Plug 'majutsushi/tagbar'")
vim.cmd("Plug 'morhetz/gruvbox'")
vim.cmd("Plug 'neoclide/coc.nvim', {'branch': 'release'}")
vim.cmd("Plug 'nvim-lua/plenary.nvim'")
vim.cmd("Plug 'nvim-telescope/telescope.nvim'")
vim.cmd("Plug 'nvim-tree/nvim-web-devicons'")
vim.cmd("Plug 'rizzatti/dash.vim'")
vim.cmd("Plug 'ryanoasis/vim-devicons'")
vim.cmd("Plug 'scrooloose/nerdcommenter'")
vim.cmd("Plug 'scrooloose/nerdtree'")
vim.cmd("Plug 'sjl/vitality.vim'")
vim.cmd("Plug 'terryma/vim-multiple-cursors'")
vim.cmd("Plug 'tpope/vim-dotenv'")
vim.cmd("Plug 'tpope/vim-endwise'")
vim.cmd("Plug 'tpope/vim-fugitive'")
vim.cmd("Plug 'tpope/vim-rails'")
vim.cmd("Plug 'vim-airline/vim-airline'")
vim.cmd("Plug 'vim-scripts/restore_view.vim'")
vim.cmd("Plug 'w0rp/ale'")
vim.cmd("Plug 'wincent/terminus'")
vim.cmd("Plug 'yggdroot/indentline'")
vim.cmd("Plug 'zorab47/procfile.vim'")

vim.cmd("call plug#end()")
