#!/usr/bin/env ruby

# checkout the readme from the master branch
`git checkout gh-pages; git checkout master README.md`

github = "https://github.com/hopsoft/"
path = `pwd`.gsub(/\n/, "")
project = path[path.rindex("/") + 1..-1]
readme_path = File.join(path, "README.md")
index_path = File.join(path, "index.md")

# write the index readme file
# be sure to prepend the jekyll front matter
File.open readme_path, "r" do |readme|
  File.open index_path, "w" do |index|

    # write the jekyll front matter
    index.puts "---"
    index.puts "title: #{project}"
    index.puts "layout: main"
    index.puts "forkme_url: #{github}#{project}"
    index.puts "---"

    code = 0
    readme.readlines.each do |line|
      code += 1 if line.include?("```")

      # convert backticks to liquid
      %w(bash ruby).each do |lang|
        line.gsub!("```#{lang}", "{% highlight #{lang} %}")
      end
      line.gsub!("```", "{% endhighlight %}")

      # convert headers so they are linkable
      if line =~ /^#+/ && code % 2 == 0
        leader = line[0, line.index(/\s/)]
        text = line[line.index(/\s./)..-1].strip
        line = "#{leader} #{text} {##{text.downcase.gsub(/\s/, "-")}}"
      end

      index.puts line
    end

    index.puts
    index.puts "---"
    index.puts
    index.puts "{% include disqus.html %}"
    index.puts "{% include forkme.html %}"
  end
end

# remove the readme
`git reset HEAD README.md; rm README.md`
